perso_galerie_homepage:
    path:     /{page}/{tags}
    defaults: { _controller: PersoGalerieBundle:Galerie:index, page: 1, tags: null }
    requirements:
        page:  \d+


perso_galerie_addPhoto:
    path:     /newPic
    defaults: { _controller: PersoGalerieBundle:Galerie:addPhoto }

perso_galerie_viewOne:
    path:      /view/{slug}
    defaults:  { _controller: PersoGalerieBundle:Galerie:voir }

perso_galerie_vote:
    path:     /{typVote}/{slug}
    defaults:  { _controller: PersoGalerieBundle:Galerie:vote }
    requirements:
        typVote:  up|down

perso_galerie_voteDuel:
    path:     /voteDuel/{idDuel}/{slug}
    defaults:  { _controller: PersoGalerieBundle:Galerie:voteDuel }

perso_galerie_duels:
    path:       /duels/{page}
    defaults: { _controller: PersoGalerieBundle:Galerie:voirDuels, page: 1 }

perso_galerie_newduel:
    path:       /newduel
    defaults: { _controller: PersoGalerieBundle:Galerie:tmpAddDuel }


#perso_galerie_duel:
#    path:       /duel/{id}
#    defaults: { _controller: PersoGalerieBundle:Galerie:voirDuel }