services:
#    perso_galerie.example:
#        class: Perso\GalerieBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    perso_galerieBundle.antispam:
        class: Perso\GalerieBundle\Antispam\PersoAntispam
        tags:
                -  { name: twig.extension }