perso_galerie:
    resource: "@PersoGalerieBundle/Resources/config/routing.yml"
    prefix:   /
    #prefix:   /{_locale}/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

perso_user:
    resource: "@PersoUserBundle/Resources/config/routing.yml"
    prefix:   /
