
perso_galerie:
    resource: "@PersoGalerieBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: "%languages_routing%"

fos_user:
    resource: "@PersoUserBundle/Resources/config/all.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
    prefix:   /{_locale}/
    requirements:
            _locale: "%languages_routing%"

perso_user:
    resource: "@PersoUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: "%languages_routing%"


oauth_register:
    pattern: /oauthRegister
    defaults: { _controller: PersoGalerieBundle:Security:oauthRegister }
my_oauth:
    resource: "@PersoGalerieBundle/Resources/config/routingSecurityOAuth.yml"
    prefix:   /oauth/