<?php

namespace Perso\GalerieBundle\Entity;

use Perso\GalerieBundle\Entity\Photo as Photo;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentairesByPhotoDesc(Photo $photo)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->join('c.photo', 'p')
            ->where('p.id = :id')
            ->setParameter('id', $photo->getId())
            ->orderBy('c.createdAt', 'DESC')
        ;

       return $qb->getQuery()->getResult();
    }
}
