<?php

namespace Perso\GalerieBundle\Entity;

//use Perso\GalerieBundle\Entity\Duel as Duel;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireDuelRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentairesByDuelDesc(Duel $duel)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->join('c.duel', 'd')
            ->where('d.id = :id')
            ->setParameter('id', $duel->getId())
            ->orderBy('c.createdAt', 'DESC')
        ;

       return $qb->getQuery()->getResult();
    }
}
