<?php

namespace Perso\GalerieBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Perso\GalerieBundle\Entity\Photo;

/**
 * VoteUserPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteUserPhotoRepository extends EntityRepository
{
    public function existVoteUser(Photo $photo)
    {
        $qb = $this->createQueryBuilder('v');
        $qb->where('v.photo = :photo')->setParameter('photo', $photo->getId());

        return $qb->getQuery()
            ->getResult();
    }
    /*
    public function getAllPhotosDesc($nombreParPage, $page)
    {
        if ($page < 1) {
            throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
        }

        $qb = $this ->createQueryBuilder('p')
            ->orderBy('p.id', 'DESC');

        $query = $qb->getQuery();
        $query->setFirstResult(($page-1) * $nombreParPage)
            ->setMaxResults($nombreParPage);

        return new Paginator($query);
    }
    */
}
