<?php

namespace Perso\GalerieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoteUserPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteUserDuelRepository extends EntityRepository
{
    /*
    public function existVoteUser(Photo $photo, $user)
    {
        //todo : vérifier l'user

        $qb = $this->createQueryBuilder('v');
        $qb->where('v.photo = :photo')
            ->setParameter('photo', $photo->getId())
            ->andWhere('v.user = :user')
            ->setParameter('user', $user);

        return $qb->getQuery()
            ->getResult();
    }
    */
}
